routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

Auth::routes();

Route::get('/', 'Auth\LoginController@showLoginForm');

Route::middleware('auth')->group(function () {
    Route::resource('locations', 'LocationsController');
    Route::resource('events', 'EventsController');
});

app/Models/Event.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Event extends Model {
    
    protected $guarded = [];

    public function getLocation() {
        return $this->hasOne(Location::class, 'id', 'location_id');
    }
}

app/Models/Location.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Location extends Model {
    protected $guarded = [];

    public function getEvents() {
        return $this->belongsToMany(Event::class, 'events', 'location_id');
    }
}

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/EventsController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\CreateEvent;
use App\Http\Requests\UpdateEvent;
use App\Models\Event;
use App\Models\Location;
use Exception;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Log;

class EventsController extends Controller {

    public function __construct() {
        $this->middleware('auth');
    }
    
    public function index(Request $request) {
        $events = $this->getEvents($request->all());
        return view('welcome', ['events' => $events]);
    }

    //In case there is some search parameter passed, we can filter it out from database.
    public function getEvents($request) {
        try {
            return Event::whereHas('getLocation')->where(function ($query) use ($request) {
                        if(isset($request['searchTerm']))
                            return $query->where('name', 'LIKE', '%'.$request['searchTerm'].'%');
                    })->get();
        } catch(Exception $e) {
            Log::info($e->getMessage().' '.$e->getLine());
            return null;
        }
    }

    private function getLocations() {
        return Location::get();
    }

    public function create() {
        try {
            return $this->atLeastOneLocationExists() ? view('events.create', ['locations' => $this->getLocations()]) : redirect()->route('locations.create')->with('error', 'To Create An Event There Must Be A Location !');
        } catch(Exception $e) {
            Log::info($e->getMessage().' '.$e->getLine());
            return view('events.create');
        }
    }

    //This method tells you if at least one location is present in the db. 
    //If not then you need to create a location first.
    private function atLeastOneLocationExists() {
        try {
            return Location::count() > 0;
        } catch(Exception $e) {
            Log::info($e->getMessage().' '.$e->getLine());
            return true;
        }
    }

    public function destroy($id) {
        try {
            Event::where('id', $id)->delete();
            return back()->with('success', 'Event Deleted !');
        } catch(Exception $e) {
            return redirect()->route('events.index')->with('error', $e->getMessage());
        }
    }

    public function show($id) {
        try {
            $event = Event::where('id', $id)->first();
            return view('events.create', ['event' => $event, 'locations' => $this->getLocations()]);
        } catch(Exception $e) {
            return redirect()->route('events.index')->with('error', $e->getMessage());
        }
    }

    public function store(CreateEvent $request) {
        try {
            $request = $request->validated();
            Event::updateOrCreate(['name' => $request['name']], $request);
            return redirect()->route('events.index')->with('success', 'Event Created !');
        } catch(Exception $e) {
            Log::info($e->getMessage().' '.$e->getLine());
            return back()->with('error', $e->getMessage().' '.$e->getLine());
        }
    }

    public function update(UpdateEvent $request) {
        try {
            $request = $request->validated();
            Event::where('id', $request['id'])->update($request);
            return back()->with('success', 'Event Updated !');
        } catch(Exception $e) {
            return back()->with('error', $e->getMessage().' '.$e->getLine());
        }
    }
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller {
    /**
     * Create a new controller instance.
     * @return void
     */
    public function __construct() {
        //$this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index() {
        return view('welcome');
    }
}

app/Http/Controllers/LocationsController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\LocationCreate;
use App\Http\Requests\LocationUpdate;
use App\Models\Location;
use Exception;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Log;
use Throwable;

class LocationsController extends Controller {

    public function __construct() {
        $this->middleware('auth');
    }

    public function index() {
        return view('locations.list', ['locations' => Location::get()]);
    }

    public function create() {
        try {
            return view('locations.create');
        } catch(Exception $e) {
            Log::info($e->getMessage().' '.$e->getLine());
            return view('locations.create');
        }
    }

    public function store(LocationCreate $request) {
        try {
            $request = $request->validated();
            Location::create($request);
            return back()->with('success', 'Location added successfully !');
        } catch(Exception $e) {
            Log::info($e->getLine().' '.$e->getMessage());
            return back()->with('error', $e->getMessage().' '.$e->getLine());
        } catch(Throwable $e) {
            Log::info($e->getLine().' '.$e->getMessage());
            return back()->with('error', $e->getMessage().' '.$e->getLine());
        }
    }

    public function destroy($id) {
        try {
            Location::where('id', $id)->delete();
            return back()->with('success', 'Location Deleted !');
        } catch(Exception $e) {
            Log::info($e->getLine().' '.$e->getMessage());
            return back()->with('error', $e->getMessage().' '.$e->getLine());
        }
    }

    public function show($id) {
        try {
            $location = Location::where('id', $id)->first();
            return view('locations.create', ['location' => $location]);
        } catch(Exception $e) { 
            Log::info($e->getLine().' '.$e->getMessage());
            return back()->with('error', $e->getMessage().' '.$e->getLine());
        }
    }

    public function update(LocationUpdate $request) {
        try {
            $request = $request->validated();
            Location::where('id', $request['id'])->update($request);
            return back()->with('success', 'Location updated successfully !');
        } catch(Exception $e) {
            Log::info($e->getLine().' '.$e->getMessage());
            return back()->with('error', $e->getMessage().' '.$e->getLine());
        } catch(Throwable $e) {
            Log::info($e->getLine().' '.$e->getMessage());
            return back()->with('error', $e->getMessage().' '.$e->getLine());
        }
    }
}

resources/views/events/create.blade.php
@extends('layouts.master')
@section('content')
    @php 
        $flag = isset($event) && $event !== null;
    @endphp
    <div class="container">
        <div class="row mt-1">
            <div class="col-md-12">
                <form method="POST" action="@if($flag) {{route('events.update', $event->id)}} @else {{route('events.store')}} @endif">
                    @csrf
                    @if($flag)
                        @method('PUT')
                        <input type="hidden" name="id" value="{{$event->id}}" />
                    @endif  
                    <div class="form-group">
                        <label for="eventName">Name</label>
                        <input type="text" class="form-control" name="name" id="eventName" @if($flag) value="{{$event->name}}" @else value="{{old('name')}}" @endif placeholder="Any event Name e.g. Rock And Roll Concert">
                        @error('name')
                        <div class="alert alert-danger mt-1">
                            {{$message}}
                        </div>
                        @enderror
                    </div>
                    <div class="form-group">
                        <label for="eventDesc">Description</label>
                        <textarea class="form-control" name="description" id="eventDesc" rows="3">@if($flag){{$event->description}}@endif</textarea>
                        @error('description')
                        <div class="alert alert-danger mt-1">
                            {{$message}}
                        </div>
                        @enderror
                    </div>
                    <div class="form-group">
                        <label for="eventDate">Date</label>
                        <input class="form-control" type="date" name="date" @if($flag) value="{{$event->date}}" @else value="{{old('date')}}" @endif>
                        @error('date')
                        <div class="alert alert-danger mt-1">
                            {{$message}}
                        </div>
                        @enderror
                    </div>
                    <div class="form-group">
                        <label for="eventLocation">Location</label>
                        <select class="form-control" id="eventLocation" name="location_id">
                            <option value="">--SELECT--</option>
                            @foreach($locations as $location)
                                <option value="{{$location->id}}" @if($flag && $location->id === $event->location_id) selected @endif>
                                    {{$location->name}}
                                </option>
                            @endforeach
                        </select>
                        @error('location_id')
                        <div class="alert alert-danger mt-1">
                            {{$message}}
                        </div>
                        @enderror
                    </div>
                    <div class="form-group">
                        <input class="btn btn-md btn-success" type="submit" @if($flag) value="Update" @else value="Create" @endif>
                    </div>
                </form>
            </div>
        </div>
    </div>
@endsection

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">{{ __('Dashboard') }}</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    {{ __('You are logged in!') }}
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/layouts/head.blade.php
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{{config('app.name')}}</title>
    <!-- Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Nunito:200,600" rel="stylesheet">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
</head>

resources/views/layouts/js.blade.php
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

resources/views/layouts/master.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
    @include('layouts.head')
    <body>
        @if(Auth::check())
            @include('layouts.nav')
            @include('layouts.top_message')
        @endif
        @yield('content')
    </body>
    @include('layouts.js')
</html>

resources/views/layouts/nav.blade.php
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="{{route('events.index')}}">{{config('app.name')}}</a>
  <a class="navbar-brand" href="{{route('locations.index')}}">Manage Locations</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      {{-- <li class="nav-item">
        <a class="nav-link" href="#">Manage Events</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Manage Locations</a>
      </li> --}}
    </ul>
    @include('layouts.searchBar')
  </div>
</nav>

resources/views/layouts/searchBar.blade.php
@php 
    $routeName = Route::currentRouteName();
@endphp
@if($routeName !== null && Str::contains($routeName, 'event'))
<form class="form-inline my-2 my-lg-0" action="" method="GET">
    <input class="form-control mr-sm-2" name="searchTerm" type="search" placeholder="Search" aria-label="Search">
    <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
</form>
@endif

resources/views/layouts/top_message.blade.php
@if(Session::has('success'))
    <div class="alert alert-success text-center">
        <h4>{{Session::get('success')}} {{Session::forget('success')}}</h4>
    </div>
@endif

@if(Session::has('error'))
    <div class="alert alert-danger text-center">
        <h4>{{Session::get('error')}} {{Session::forget('error')}}</h4>
    </div>
@endif

resources/views/locations/create.blade.php
@extends('layouts.master')
@section('content')
    @php 
        $flag = isset($location) && $location !== null;
    @endphp
    <div class="container">
        <div class="row mt-1">
            <div class="col-md-12">
                <form method="POST" action="@if($flag) {{route('locations.update', $location->id)}} @else {{route('locations.store')}} @endif">
                    @csrf
                    @if($flag)
                        @method('PUT')
                        <input type="hidden" name="id" value="{{$location->id}}" />
                    @endif  
                    <div class="form-group">
                        <label for="locationName">Name</label>
                        <input type="text" class="form-control" name="name" id="locationName" @if($flag) value="{{$location->name}}" @else value="{{old('name')}}" @endif placeholder="Any Location Name e.g. Punjab">
                        @error('name')
                        <div class="alert alert-danger mt-1">
                            {{$message}}
                        </div>
                        @enderror
                    </div>
                    <div class="form-group">
                        <label for="locationDesc">Description</label>
                        <textarea class="form-control" name="description" id="locationDesc" rows="3">@if($flag){{$location->description}}@endif</textarea>
                        @error('description')
                        <div class="alert alert-danger mt-1">
                            {{$message}}
                        </div>
                        @enderror
                    </div>
                    <div class="form-group">
                        <input class="btn btn-md btn-success" type="submit" @if($flag) value="Update" @else value="Create" @endif>
                    </div>
                </form>
            </div>
        </div>
    </div>
@endsection

resources/views/locations/list.blade.php
@extends('layouts.master')
@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-12 text-center">
                <a href="{{route('locations.create')}}" class="btn btn-md btn-success mt-1">Create A New Location</a>
                @if(isset($locations) && $locations->count() > 0)
                    <table class="table mt-1">
                        <thead>
                            <tr>
                                <th>Name</th>
                                <th>Description</th>
                                <th>Edit / Delete</th>
                            </tr>
                        </thead>
                        <tbody>
                            @forelse($locations as $Location)
                            <tr>
                                <td>{{$Location->name}}</td>
                                <td>{{$Location->description}}</td>
                                <td>
                                    <a href="{{route('locations.update', $Location->id)}}">
                                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-pencil-fill" viewBox="0 0 16 16">
                                            <path d="M12.854.146a.5.5 0 0 0-.707 0L10.5 1.793 14.207 5.5l1.647-1.646a.5.5 0 0 0 0-.708l-3-3zm.646 6.061L9.793 2.5 3.293 9H3.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.207l6.5-6.5zm-7.468 7.468A.5.5 0 0 1 6 13.5V13h-.5a.5.5 0 0 1-.5-.5V12h-.5a.5.5 0 0 1-.5-.5V11h-.5a.5.5 0 0 1-.5-.5V10h-.5a.499.499 0 0 1-.175-.032l-.179.178a.5.5 0 0 0-.11.168l-2 5a.5.5 0 0 0 .65.65l5-2a.5.5 0 0 0 .168-.11l.178-.178z"/>
                                        </svg>
                                    </a>
                                    &nbsp;&nbsp;&nbsp;
                                    <a onclick="$('#deleteLocation-{{$Location->id}}').submit();">
                                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-trash-fill" viewBox="0 0 16 16">
                                            <path d="M2.5 1a1 1 0 0 0-1 1v1a1 1 0 0 0 1 1H3v9a2 2 0 0 0 2 2h6a2 2 0 0 0 2-2V4h.5a1 1 0 0 0 1-1V2a1 1 0 0 0-1-1H10a1 1 0 0 0-1-1H7a1 1 0 0 0-1 1H2.5zm3 4a.5.5 0 0 1 .5.5v7a.5.5 0 0 1-1 0v-7a.5.5 0 0 1 .5-.5zM8 5a.5.5 0 0 1 .5.5v7a.5.5 0 0 1-1 0v-7A.5.5 0 0 1 8 5zm3 .5v7a.5.5 0 0 1-1 0v-7a.5.5 0 0 1 1 0z"/>
                                        </svg>
                                    </a>
                                    <form id="deleteLocation-{{$Location->id}}" method="POST" action="{{route('locations.destroy', $Location->id)}}">
                                        @csrf
                                        @method('DELETE')
                                    </form>
                                </td>
                            </tr>
                            @empty
                            <tr><td colspan="5">No Locations Found !!</td></tr>    
                            </div>
                        </tbody>
                    </table>
                    @endforelse
                @else 
                    <div class="alert alert-danger mt-1">
                        No Locations Found !!
                    </div>
                @endif
            </div>
        </div>
    </div>
@endsection